Star Education Society
Salarhabibi-amir/Star-Education-Society pull request #1
Opened 2023-05-23 20:24 UTC by Salarhabibi-amir

I have customized the Capstone template for the Star Education Society which is an Academic organisation. I tried to make the design similar to the Capstone template. I have create only the index and about page. I used javascript to create the Feature Teacher section dynamic.

2023-05-23 21:45 UTC, IngDavidTM requested changes
## Hi @Salarhabibi-amir  🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-23 21:45 UTC, IngDavidTM commented on README.md
> +I would like to thank from Microvers Because of preparing a great envirnment for everyone in all over the globe.
- [ ] Kindly, as a project requirement, the README should contain an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/) :+1: :100:.

2023-05-23 21:45 UTC, IngDavidTM commented on style.css
- [ ] While you did a fantastic job :+1:, as a project requirement the pages should use the exact same colors, for text, backgrounds, borders, etc, from the original design.
**Hint:** Basic color swatch: #272A31, #EC5242, #D3D3D3

2023-05-23 21:45 UTC, IngDavidTM commented on about.html
> +                <h1 class=" fw-red fw-bolder">STAR EDUCATIONAL <br>SOCEITY 2023</h1>
- [ ] Great work on recognizing the titles within your project :+1:. However, it is important to note that for the sake of semantic structure on your webpage, it is recommended to have only a single `h1` tag per page.

2023-05-23 21:45 UTC, IngDavidTM commented on index.html
> +                    <div class="icon"><img src="assets/images/discourse.png" alt=""></div>
- [ ] You've done an excellent job meeting the project requirement of adding images :+1:. However, it is crucial to ensure that your webpage is accessible to all users. To achieve accessibility, please review the images on both the index.html and about.html pages to ensure they have proper alt attributes. These alt attributes provide alternative text descriptions for the images, making them accessible to individuals who may have visual impairments or are using assistive technologies.

2023-05-24 00:01 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @Salarhabibi-amir , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 00:07 UTC, merged

2023-05-26 21:31 UTC, MohamedRoshdy2021 commented on script.js
> +const seeMoreBtn = document.getElementById('moreBtn');
there is a small issue that needs to be Fixed over here